-- Phase 4: Vector Embeddings & Semantic Search
-- Enable pgvector extension and create embeddings table

-- Enable pgvector extension for vector similarity search
CREATE EXTENSION IF NOT EXISTS vector;

-- Create embeddings table
CREATE TABLE IF NOT EXISTS embeddings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  chunk_id UUID NOT NULL REFERENCES chunks(id) ON DELETE CASCADE,
  document_id UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  embedding vector(1536) NOT NULL,  -- OpenAI text-embedding-3-small dimensions
  model TEXT NOT NULL DEFAULT 'text-embedding-3-small',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS embeddings_chunk_id_idx ON embeddings(chunk_id);
CREATE INDEX IF NOT EXISTS embeddings_document_id_idx ON embeddings(document_id);
CREATE INDEX IF NOT EXISTS embeddings_user_id_idx ON embeddings(user_id);

-- Create HNSW index for fast vector similarity search
-- Using cosine distance (vector_cosine_ops) which is standard for embeddings
-- m=16 and ef_construction=64 are good defaults for most use cases
CREATE INDEX IF NOT EXISTS embeddings_embedding_idx 
ON embeddings 
USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

-- Enable Row Level Security
ALTER TABLE embeddings ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can view their own embeddings
CREATE POLICY "Users can view their own embeddings"
  ON embeddings
  FOR SELECT
  USING (
    user_id = auth.uid()
    OR
    -- Allow viewing embeddings from public documents
    document_id IN (
      SELECT id FROM documents WHERE is_public = true
    )
  );

-- RLS Policy: Users can insert embeddings for their own chunks
CREATE POLICY "Users can insert embeddings for their own chunks"
  ON embeddings
  FOR INSERT
  WITH CHECK (
    user_id = auth.uid()
    AND
    chunk_id IN (
      SELECT c.id FROM chunks c
      JOIN documents d ON c.document_id = d.id
      WHERE d.user_id = auth.uid()
    )
  );

-- RLS Policy: Users can delete their own embeddings
CREATE POLICY "Users can delete their own embeddings"
  ON embeddings
  FOR DELETE
  USING (user_id = auth.uid());

-- Create helper function for semantic search
-- This function performs vector similarity search and returns relevant chunks
CREATE OR REPLACE FUNCTION search_chunks_semantic(
  query_embedding vector(1536),
  match_threshold float DEFAULT 0.7,
  match_count int DEFAULT 10,
  filter_user_id uuid DEFAULT NULL
)
RETURNS TABLE (
  chunk_id uuid,
  document_id uuid,
  chunk_index int,
  content text,
  similarity float,
  document_name text,
  document_file_type text
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    c.id AS chunk_id,
    c.document_id,
    c.chunk_index,
    c.content,
    1 - (e.embedding <=> query_embedding) AS similarity,
    d.file_name AS document_name,
    d.file_type AS document_file_type
  FROM embeddings e
  JOIN chunks c ON e.chunk_id = c.id
  JOIN documents d ON c.document_id = d.id
  WHERE
    (filter_user_id IS NULL OR e.user_id = filter_user_id OR d.is_public = true)
    AND 1 - (e.embedding <=> query_embedding) > match_threshold
  ORDER BY e.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- Grant execute permission on the search function
GRANT EXECUTE ON FUNCTION search_chunks_semantic TO authenticated;

-- Add comment for documentation
COMMENT ON TABLE embeddings IS 'Stores vector embeddings for semantic search. Each chunk has one embedding generated by OpenAI text-embedding-3-small model.';
COMMENT ON FUNCTION search_chunks_semantic IS 'Performs semantic search across chunks using vector similarity. Returns chunks ranked by relevance to the query embedding.';
